import type { CrmCase, Operator } from "./types"

export const OPERATORS: Operator[] = [
  { id: "op-ec", name: "Weronika Sadowska", initials: "WS", color: "bg-emerald-500" },
  { id: "op-gp", name: "Ilona Marchenko", initials: "IM", color: "bg-amber-500" },
  { id: "op-pk", name: "Pavel Rusetski", initials: "PR", color: "bg-violet-500" },
  { id: "op-dl", name: "Daniel Wozniak", initials: "DW", color: "bg-sky-500" },
  { id: "op-al", name: "Aleh Miranovich", initials: "AM", color: "bg-rose-500" },
]

const HOUR = 1000 * 60 * 60
// Fixed reference instant (not Date.now()) so every seeded timestamp is
// identical whether this module is evaluated on the server or re-evaluated
// in the browser bundle — otherwise the two evaluations happen at different
// wall-clock times and every "now"-relative demo timestamp would mismatch
// between SSR and hydration.
const now = new Date("2026-09-25T12:00:00.000Z").getTime()
const iso = (offsetHours: number) => new Date(now + offsetHours * HOUR).toISOString()

function makeCase(partial: Partial<CrmCase> & Pick<CrmCase, "id" | "displayName" | "boards">): CrmCase {
  return {
    title: partial.displayName,
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "undefined",
    priority: "normal",
    tags: [],
    lastActivityAt: iso(-1),
    createdAt: iso(-48),
    clinic: "Pana Medica",
    tasks: [],
    notes: "",
    timeline: [
      { id: `${partial.id}-t1`, type: "status", at: iso(-48), text: "Case created" },
    ],
    ...partial,
  }
}

export const CASES: CrmCase[] = [
  makeCase({
    id: "IE-60276",
    title: "Nowicki Marek",
    displayName: "Nowicki Marek",
    phone: "+48 611 924 357",
    channelType: "Chat",
    channelPlatform: "internal",
    service: "Restorative Dentistry",
    doctor: "Bohdan Marchenko",
    qualification: "qualified",
    priority: "high",
    tags: ["WS"],
    assignedTo: "Weronika Sadowska",
    nextContactAt: iso(6),
    lastActivityAt: iso(-1),
    createdAt: iso(-120),
    clinic: "Pana Medica",
    boards: { leads: "call_later", deals: "no_show" },
    unread: 0,
    lastMessage: "Rozmowa z pacjentką, poprosiła o telefon za tydzień",
    notes: "Trzeba zadzwonić 30.09. Kwestia finansowa — zaproponować raty.",
    tasks: [
      { id: "t1", title: "Zadzwoń i zaproponuj pacjentce wizytę", done: false, due: iso(4), assignee: "Aleh" },
      { id: "t2", title: "Uściślij budżet pacjentki", done: true, assignee: "Weronika Sadowska" },
    ],
    timeline: [
      { id: "e1", type: "status", at: iso(-120), text: "Case created from Instagram inquiry" },
      { id: "e2", type: "call", at: iso(-30), text: "Outgoing call · 4m 12s · Talk time 3m 40s" },
      { id: "e3", type: "note", at: iso(-2), text: "Rozmowa z pacjentką, brak możliwości finansowych. Poprosiła o telefon za tydzień i zapisanie na leczenie.", author: "Weronika Sadowska" },
      { id: "e4", type: "status", at: iso(-1), text: "Moved to Call Later" },
    ],
  }),
  makeCase({
    id: "IE-54867",
    title: "Symonovich Kseniya",
    displayName: "Symonovich Kseniya",
    phone: "+48 712 483 209",
    channelType: "Call",
    channelPlatform: "phone",
    service: "Orthodontics",
    doctor: "Marzanna Wilczek",
    qualification: "qualified",
    priority: "normal",
    tags: ["IM"],
    assignedTo: "Ilona Marchenko",
    nextContactAt: iso(24),
    lastActivityAt: iso(-3),
    boards: { leads: "qualification" },
    lastMessage: "Call · 2026-06-03 · Qualified",
    tasks: [
      { id: "t1", title: "Follow up after consultation", done: false, assignee: "Ilona Marchenko" },
      { id: "t2", title: "Send price list", done: false, assignee: "Ilona Marchenko" },
    ],
  }),
  makeCase({
    id: "IE-18196",
    title: "INSTAGRAM_203847612",
    displayName: "INSTAGRAM_203847612",
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "undefined",
    priority: "low",
    assignedTo: "Weronika Sadowska",
    boards: { leads: "new", patients: "appt_scheduled" },
    lastActivityAt: iso(-0.3),
    lastMessage: "Dzień dobry! Chciałabym poznać ceny implantacji",
    unread: 2,
    tasks: [{ id: "t1", title: "INSTAGRAM_203847612", done: false, assignee: "Weronika Sadowska" }],
  }),
  makeCase({
    id: "IE-70876",
    title: "Call +48661408392",
    displayName: "Call +48661408392",
    phone: "+48 661 408 392",
    channelType: "Call",
    channelPlatform: "phone",
    qualification: "undefined",
    priority: "normal",
    boards: { leads: "new" },
    lastActivityAt: iso(-1.4),
    lastMessage: "Missed call",
  }),
  makeCase({
    id: "IE-60211",
    title: "Melnychuk Oksana",
    displayName: "Melnychuk Oksana",
    phone: "+48 734 xx xx",
    channelType: "Call",
    channelPlatform: "phone",
    service: "Prosthodontics",
    qualification: "qualified",
    priority: "normal",
    boards: { leads: "converted", deals: "scheduled" },
    lastActivityAt: iso(-11 / 60),
    doctor: "Piotr Zawadzki",
  }),
  makeCase({
    id: "IE-55950",
    title: "Artem Kowalczyk",
    displayName: "Artem Kowalczyk",
    phone: "+48 819 xx xx",
    channelType: "Call",
    channelPlatform: "phone",
    service: "Orthodontics",
    qualification: "qualified",
    boards: { leads: "converted", deals: "scheduled" },
    lastActivityAt: iso(-25 / 60),
  }),
  makeCase({
    id: "IE-00211",
    title: "Maryna Sokolova",
    displayName: "Maryna Sokolova",
    phone: "+48 622 xx xx",
    channelType: "Call",
    channelPlatform: "phone",
    service: "Orthodontics",
    qualification: "unqualified",
    priority: "low",
    boards: { leads: "failed" },
    lastActivityAt: iso(-59 / 60),
    notes: "20.0... nie jest zainteresowana leczeniem teraz",
  }),
  makeCase({
    id: "IE-33001",
    title: "TELEGRAM_390518274",
    displayName: "TELEGRAM_390518274",
    channelType: "Chat",
    channelPlatform: "telegram",
    qualification: "undefined",
    boards: { leads: "qualification" },
    lastActivityAt: iso(-34 / 60),
    lastMessage: "Dzień dobry! W naszej klinice jest możliwość podziału opłaty bez odsetek",
    unread: 1,
  }),
  makeCase({
    id: "IE-40213",
    title: "Marzanna Wilczek",
    displayName: "Marzanna Wilczek",
    phone: "+48 881 xx xx",
    channelType: "Call",
    channelPlatform: "phone",
    service: "Orthodontics",
    qualification: "qualified",
    boards: { leads: "qualification" },
    lastActivityAt: iso(-1),
  }),
  makeCase({
    id: "IE-71001",
    title: "Call +48592817364",
    displayName: "Call +48592817364",
    phone: "+48 592 817 364",
    channelType: "Call",
    channelPlatform: "phone",
    qualification: "unqualified",
    priority: "low",
    boards: { leads: "failed" },
    lastActivityAt: iso(-1),
    notes: "nie dzwonić ponownie, pani poprosiła",
  }),
  makeCase({
    id: "IE-52001",
    title: "Tsimoshka Andrei",
    displayName: "Tsimoshka Andrei",
    phone: "+48 863 xx xx",
    channelType: "Call",
    channelPlatform: "phone",
    service: "Endodontics",
    qualification: "qualified",
    boards: { leads: "qualification" },
    lastActivityAt: iso(-1),
  }),
  makeCase({
    id: "IE-22603",
    title: "INSTAGRAM_552910837",
    displayName: "INSTAGRAM_552910837",
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "undefined",
    boards: { leads: "new" },
    lastActivityAt: iso(-51 / 60),
    unread: 3,
    lastMessage: "Ile kosztuje konsultacja?",
  }),
  makeCase({
    id: "IE-40990",
    title: "Kovalchuk Iryna",
    displayName: "Kovalchuk Iryna",
    phone: "+48 714 xx xx",
    channelType: "Call",
    channelPlatform: "phone",
    service: "2 Services",
    qualification: "qualified",
    boards: { leads: "qualification" },
    lastActivityAt: iso(-2),
  }),
  makeCase({
    id: "IE-51222",
    title: "Novak Restorative",
    displayName: "Novak Tomasz",
    phone: "+48 502 xx xx",
    channelType: "Chat",
    channelPlatform: "internal",
    service: "Restorative Dentistry",
    qualification: "qualified",
    boards: { leads: "qualification" },
    lastActivityAt: iso(-1),
    notes: "Potrzebna konsultacja ze zdjęciem RTG",
  }),
  makeCase({
    id: "IE-71503",
    title: "Call +48617xxx",
    displayName: "Call +48617xxx",
    phone: "+48 617 xxx",
    channelType: "Call",
    channelPlatform: "phone",
    qualification: "unqualified",
    priority: "low",
    boards: { leads: "failed" },
    lastActivityAt: iso(-2),
    notes: "nie dzwonić ponownie",
  }),
  makeCase({
    id: "IE-90112",
    title: "Yasenchuk Halyna",
    displayName: "Yasenchuk Halyna",
    phone: "+48 748 xx xx",
    channelType: "Call",
    channelPlatform: "phone",
    service: "3 Services",
    qualification: "qualified",
    boards: { leads: "qualification" },
    lastActivityAt: iso(-2),
  }),
  makeCase({
    id: "IE-31441",
    title: "Kavalchuk Vera",
    displayName: "Kavalchuk Vera",
    phone: "+48 936 xx xx",
    channelType: "Call",
    channelPlatform: "phone",
    service: "Dental Implants",
    qualification: "qualified",
    boards: { leads: "qualification" },
    lastActivityAt: iso(-2),
    tags: ["IM"],
  }),
  makeCase({
    id: "IE-88112",
    title: "Website Form Intake",
    displayName: "Website Form Intake",
    channelType: "Web Form",
    channelPlatform: "website",
    qualification: "undefined",
    boards: { deals: "scheduled" },
    lastActivityAt: iso(-3),
  }),
  makeCase({
    id: "IE-40332",
    title: "Kowalczyk Natalia",
    displayName: "Kowalczyk Natalia",
    phone: "+48 519 264 807",
    channelType: "Call",
    channelPlatform: "phone",
    qualification: "qualified",
    boards: { deals: "scheduled" },
    lastActivityAt: iso(-4),
  }),
  makeCase({
    id: "IE-77213",
    title: "Zhukouski Aliaksandr",
    displayName: "Zhukouski Aliaksandr",
    phone: "+48 683 527 419",
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "qualified",
    boards: { deals: "post_visit" },
    lastActivityAt: iso(-5),
  }),
  makeCase({
    id: "IE-91882",
    title: "Dzmitry Shevtsov",
    displayName: "Dzmitry Shevtsov",
    phone: "+48 604 158 732",
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "qualified",
    boards: { deals: "post_visit" },
    lastActivityAt: iso(-6),
  }),
  makeCase({
    id: "IE-10023",
    title: "Bahdanovich Yauhen",
    displayName: "Bahdanovich Yauhen",
    phone: "+48 691 372 048",
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "qualified",
    boards: { patients: "appt_scheduled" },
    doctor: "Aleh Yanushkevich",
    lastActivityAt: iso(-16),
  }),
  makeCase({
    id: "IE-10098",
    title: "Zofia",
    displayName: "Zofia",
    phone: "692 481 375",
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "undefined",
    boards: { patients: "new_patient" },
    lastActivityAt: iso(-20),
  }),
  makeCase({
    id: "IE-10111",
    title: "Ostapchuk Svitlana",
    displayName: "Ostapchuk Svitlana",
    phone: "+48 775 903 261",
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "qualified",
    boards: { patients: "returning" },
    doctor: "Piotr Zawadzki",
    lastActivityAt: iso(-260),
  }),
  makeCase({
    id: "IE-10145",
    title: "Kazlouski Uladzimir",
    displayName: "Kazlouski Uladzimir",
    phone: "774 520 869",
    channelType: "Call",
    channelPlatform: "phone",
    qualification: "qualified",
    boards: { patients: "returning" },
    lastActivityAt: iso(-284),
  }),
  makeCase({
    id: "IE-10166",
    title: "Bandarenka Iryna",
    displayName: "Bandarenka Iryna",
    channelType: "Chat",
    channelPlatform: "whatsapp",
    qualification: "qualified",
    boards: { patients: "new_patient" },
    lastActivityAt: iso(-4),
  }),
  makeCase({
    id: "IE-10188",
    title: "Fesenko Olena",
    displayName: "Fesenko Olena",
    phone: "+48 942 xx xx",
    channelType: "Call",
    channelPlatform: "phone",
    service: "Periodontology",
    qualification: "qualified",
    boards: { leads: "qualification" },
    lastActivityAt: iso(-2),
    tags: ["DW"],
  }),
  makeCase({
    id: "IE-10199",
    title: "Talkachova Elvira",
    displayName: "Talkachova Elvira",
    phone: "+48 683 197 542",
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "undefined",
    boards: { leads: "new" },
    lastActivityAt: iso(-2.5),
    unread: 1,
  }),
  makeCase({
    id: "IE-10210",
    title: "Kavaliova Hanna",
    displayName: "Kavaliova Hanna",
    phone: "+48 630 xx xx",
    channelType: "Chat",
    channelPlatform: "instagram",
    qualification: "undefined",
    boards: { leads: "waiting" },
    lastActivityAt: iso(-3),
  }),
]

export function getCaseById(id: string) {
  return CASES.find((c) => c.id === id)
}
